CONFIG_VIDEO=y
CONFIG_SPI=y
CONFIG_VIDEO_ARDUCAM_MEGA=y
CONFIG_LOG=y
CONFIG_PRINTK=y

# Video buffer pool configuration (320x240 RGB565 is 153600 bytes. Heap size set to 320KB for 2 buffers)
CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=327680
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=4
