CONFIG_VIDEO=y
CONFIG_SPI=y
CONFIG_VIDEO_ARDUCAM_MEGA=y
CONFIG_LOG=y
CONFIG_PRINTK=y

# Video buffer pool configuration (320x320 RGB565 is 204800 bytes. Heap size set to 440KB for 2 buffers)
CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=440000
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=2

# C++ support for Edge Impulse SDK
CONFIG_CPP=y
CONFIG_STD_CPP11=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# Hardware FPU support for float calculation in Edge Impulse SDK
CONFIG_FPU=y

# Stack protection to catch stack overflow immediately
CONFIG_HW_STACK_PROTECTION=y
CONFIG_STACK_SENTINEL=y

# Main stack size set to 32KB (Optimized to release RAM for larger TFLite arena)
CONFIG_MAIN_STACK_SIZE=32768
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=8192
